// <auto-generated />
using DirectoryChangeApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DirectoryChangeApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DirectoryChangeApp.Data.Models.DirectoryState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryPath")
                        .IsUnique();

                    b.ToTable("DirectoryStates");
                });

            modelBuilder.Entity("DirectoryChangeApp.Data.Models.FileItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DirectoryStateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryStateId");

                    b.ToTable("FileItems");
                });

            modelBuilder.Entity("DirectoryChangeApp.Data.Models.FileItemEntity", b =>
                {
                    b.HasOne("DirectoryChangeApp.Data.Models.DirectoryState", "DirectoryState")
                        .WithMany("FileItems")
                        .HasForeignKey("DirectoryStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectoryState");
                });

            modelBuilder.Entity("DirectoryChangeApp.Data.Models.DirectoryState", b =>
                {
                    b.Navigation("FileItems");
                });
#pragma warning restore 612, 618
        }
    }
}
